# Generated by Django 4.2.9 on 2026-07-07 18:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('role', models.CharField(choices=[('developer', 'Developer'), ('senior_developer', 'Senior Developer'), ('tech_lead', 'Tech Lead'), ('devops_engineer', 'DevOps Engineer'), ('qa_engineer', 'QA Engineer'), ('product_manager', 'Product Manager'), ('engineering_manager', 'Engineering Manager')], max_length=30)),
                ('status', models.CharField(choices=[('active', 'Active'), ('on_leave', 'On Leave'), ('remote', 'Remote'), ('inactive', 'Inactive')], default='active', max_length=20)),
                ('slack_handle', models.CharField(blank=True, max_length=100)),
                ('github_username', models.CharField(blank=True, max_length=100)),
                ('date_joined', models.DateField(auto_now_add=True)),
                ('department', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employees', to='employees.department')),
            ],
            options={
                'ordering': ['last_name', 'first_name'],
            },
        ),
    ]
