# Generated by Django 4.2.9 on 2026-07-07 18:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HardwareAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset_id', models.CharField(max_length=50, unique=True)),
                ('asset_type', models.CharField(choices=[('laptop', 'Laptop'), ('desktop', 'Desktop'), ('monitor', 'Monitor'), ('phone', 'Phone'), ('tablet', 'Tablet'), ('server', 'Server'), ('other', 'Other')], max_length=20)),
                ('manufacturer', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
                ('serial_number', models.CharField(max_length=100, unique=True)),
                ('status', models.CharField(choices=[('available', 'Available'), ('assigned', 'Assigned'), ('in_repair', 'In Repair'), ('retired', 'Retired')], default='available', max_length=20)),
                ('purchase_date', models.DateField()),
                ('warranty_expiry', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hardware_assets', to='employees.employee')),
            ],
            options={
                'ordering': ['asset_id'],
            },
        ),
    ]
