# Generated by Django 4.2.9 on 2026-07-07 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceHealth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_name', models.CharField(max_length=100, unique=True)),
                ('url', models.URLField()),
                ('status', models.CharField(choices=[('Healthy', 'Healthy'), ('Degraded', 'Degraded'), ('Down', 'Down'), ('Maintenance', 'Maintenance')], default='Healthy', max_length=20)),
                ('response_time_ms', models.PositiveIntegerField(default=0, help_text='Response time in ms')),
                ('uptime_percentage', models.FloatField(default=100.0)),
                ('last_checked', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Services Health',
                'ordering': ['service_name'],
            },
        ),
    ]
